config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments
  end
  devise_for :users
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
    can :read, :all
    can :manage, Comment do |comment|
      comment.user == user
    end
  end

    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_admins

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :joins
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :event
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_many :comments
  has_many :joins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create(params[:comment].permit(:content))
    @comment.user = current_user
    @comment.save

    redirect_to event_path(@event)

  end

  def destroy
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id]).destroy
    redirect_to event_path(@event)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :content, :date_of_event)
    end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %>
<p><%= time_ago_in_words(comment.created_at) %>
  <% if can? :update, comment %>
<p><%= link_to "Delete",[comment.event, comment], method: :delete %> </p>
  <% end %>

app/views/comments/_form.html.erb
<%= form_for([@event, @event.comments.build]) do |f| %>
    <p>
      <%= f.text_area :content %>
    </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :event_content %>
  </div>

  <div class="field">
    <%= form.label :date_of_event %>
    <%= form.datetime_select :date_of_event, id: :event_date_of_event %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Date of event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.content %></td>
        <td><%= event.date_of_event %></td>
        <td><%= link_to 'Show', event %></td>
        <% if can? :update, event %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>Date of event:</strong>
  <%= @event.date_of_event %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<h2> <%= @event.comments.count %> Comments</h2>
<%= render @event.comments %>
<h3>Add a comment</h3>
<%= render 'comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "EVENTS", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
          <% if user_signed_in? -%>
                <li><%= link_to 'Account', edit_user_registration_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else -%>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end -%>
        </nav>
      </div>
    </div>
  </header>
    <%= yield %>
  </body>
</html>